name: Integration Actions to Build Custom Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_pull_request_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      PORT: ${{ secrets.PORT }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4