name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Template Check
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASE: ${{ secrets.DATABASE }}
      PORT: ${{ secrets.PORT }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build application artifact
      - name: Build application artifact
        run: zip -r webapp.zip .

      # Step 3: Install Packer
      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      # Step 4: Check for proper formatting
      - name: Format Packer Template
        run: |
          if ! packer fmt -check -diff application-custom-image.pkr.hcl; then
            echo "Packer template is not properly formatted. Please run 'packer fmt' to format."
            exit 1
          fi

      # Step 5: Initialize Packer
      - name: Initialize Packer
        run: packer init application-custom-image.pkr.hcl

      # Step 6: Validate and format Packer template
      - name: Validate Packer Template
        run: |
          packer validate application-custom-image.pkr.hcl
          packer fmt application-custom-image.pkr.hcl